# Generated by Django 6.0.2 on 2026-02-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='mood',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='sleep',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
